version: "3.8"

services:
  redis:
    image: mysql:5.7.43
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
