version: "3.8"

services:
  redis:
    image: redis:6.2.13
    container_name: redis
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
     - 6379:6379
    volumes:
     - /etc/timezone:/etc/timezone
     - ./data:/data
     - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
