version: "3.8"

services:
  mongo:
    image: mongo:5.0.20
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
     - "27017:27017/tcp"
    volumes:
     - /etc/timezone:/etc/timezone
     - ./data:/data/db